name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    name: Build PDF
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TeX Live Base
        run: |
          sudo apt update
          sudo apt install -y texlive-latex-base

      - name: Install TeX Extras
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: |
            latexmk
            texlive-latex-extra
            texlive-science
            texlive-fonts-extra
      
      - name: Restore Cache Files
        uses: actions/cache/restore@v4
        with:
          key: pdflatex-cache
          path: |
            **/*.aux
            main.aux
            main.fdb_latexmk
            main.fls
            main.out
            main.toc

      - name: Compile PDF File
        run: latexmk -pdflatex -interaction=nonstopmode -file-line-error main.tex

      - name: Store Cache Files
        uses: actions/cache/save@v4
        with:
          key: pdflatex-cache
          path: |
            **/*.aux
            main.aux
            main.fdb_latexmk
            main.fls
            main.out
            main.toc
      
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf

  build-webpage:
    runs-on: ubuntu-latest
    name: Build Webpage
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TeX Live
        run: |
          sudo apt update
          sudo apt install -y texlive-latex-base

      - name: Install TeX Extras
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: |
            texlive-latex-extra
            texlive-science
            texlive-fonts-extra
      
      - name: Restore Cache Files
        uses: actions/cache/restore@v4
        with:
          key: make4ht-cache
          path: |
            **/*.aux
            main.aux
            main.4ct
            main.4tc
            main.dvi
            main.idv
            main.lg
            main.tmp
            main.xref
            

      - name: Compile Webpage File
        run: make4ht -u -d webpage main.tex "mathml"

      - name: Store Cache Files
        uses: actions/cache/save@v4
        with:
          key: make4ht-cache
          path: |
            **/*.aux
            main.aux
            main.4ct
            main.4tc
            main.dvi
            main.idv
            main.lg
            main.tmp
            main.xref
      
      - name: Upload Webpage file
        uses: actions/upload-artifact@v4
        with:
          name: Webpage
          path: webpage/
