name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    name: Build PDF
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TeX Environment
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: |
            texlive-full
      
      - name: Restore Cache Files
        uses: actions/cache/restore@v4
        with:
          key: pdflatex-cache
          path: |
            **/*.aux
            main.aux
            main.fdb_latexmk
            main.fls
            main.out
            main.toc

      - name: Compile PDF File
        run: latexmk -pdflatex -interaction=nonstopmode -file-line-error main.tex

      - name: Store Cache Files
        uses: actions/cache/save@v4
        with:
          key: pdflatex-cache
          path: |
            **/*.aux
            main.aux
            main.fdb_latexmk
            main.fls
            main.out
            main.toc
      
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
