name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build PDF and Webpage
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TeX Live Base
        run: |
          sudo apt update
          sudo apt install -y texlive-latex-extra texlive-science texlive-fonts-extra texlive-extra-utils

      - name: Install TeX Extras
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: |
            latexmk
          execute_install_scripts: true

      - name: Compile PDF File
        run: latexmk -pdflatex -interaction=nonstopmode -file-line-error main.tex
      
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf

      - name: Compile Webpage File
        run: make4ht -u -d webpage main.tex "mathml"

      - name: Build Webpage Folder
        run:
          cp main.pdf webpage/latest.pdf
      
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: webpage/
  
  deploy-pages:
    name: Deploy GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4